// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddLANPrinter(arg1:string):Promise<void>;

export function CheckLANPrinterStatus(arg1:string):Promise<boolean>;

export function ConfigureFirewall():Promise<void>;

export function ConfirmQuit():Promise<boolean>;

export function ConfirmRemoveLANPrinter(arg1:string):Promise<boolean>;

export function DisableAutostart():Promise<void>;

export function DownloadLogs():Promise<void>;

export function EnableAutostart():Promise<void>;

export function GetLANSettings():Promise<main.LANSettings>;

export function GetPrinterIp(arg1:string):Promise<string>;

export function IsAutostartEnabled():Promise<boolean>;

export function SkipFirewallPrompt():Promise<void>;

export function Status():Promise<main.Status>;
