// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLANPrinter(arg1) {
  return window['go']['main']['App']['AddLANPrinter'](arg1);
}

export function CheckLANPrinterStatus(arg1) {
  return window['go']['main']['App']['CheckLANPrinterStatus'](arg1);
}

export function ConfigureFirewall() {
  return window['go']['main']['App']['ConfigureFirewall']();
}

export function ConfirmQuit() {
  return window['go']['main']['App']['ConfirmQuit']();
}

export function ConfirmRemoveLANPrinter(arg1) {
  return window['go']['main']['App']['ConfirmRemoveLANPrinter'](arg1);
}

export function DisableAutostart() {
  return window['go']['main']['App']['DisableAutostart']();
}

export function DownloadLogs() {
  return window['go']['main']['App']['DownloadLogs']();
}

export function EnableAutostart() {
  return window['go']['main']['App']['EnableAutostart']();
}

export function GetLANSettings() {
  return window['go']['main']['App']['GetLANSettings']();
}

export function GetPrinterIp(arg1) {
  return window['go']['main']['App']['GetPrinterIp'](arg1);
}

export function IsAutostartEnabled() {
  return window['go']['main']['App']['IsAutostartEnabled']();
}

export function SkipFirewallPrompt() {
  return window['go']['main']['App']['SkipFirewallPrompt']();
}

export function Status() {
  return window['go']['main']['App']['Status']();
}
